### ISSUE TITLE
BackNet disconnecting after connection on port 1604

### ISSUE THREAD

**Issue by thomas1131** [valsov/BackNet#1]
For some reason it automatically disconnects

EDIT: The random string thing was because i was using ctrl + F5 on visual studio

**Comment by valsov** [comment]
Sorry I didn't see your issue earlier. This project is no longer being maintained, but maybe with more details I could help you with your issue. Don't expect a fast reply, I'm busy those days...

**Comment by valsov** [comment]
I'm not reproducing the disconnection just by connection non the port 1604, then sending commands to the slave, so I will need more context in order to reproduce the bug.
